/**
 * A summary — compressed representation of history (or other summaries).
 *
 * Meta-summaries use the same interface with source_type='summary'.
 * Same table, same code paths, different interpretation.
 */
import type { SummaryId } from './SummaryId';
import type { PersonaId } from './PersonaId';
import type { ISOTimestamp } from './ISOTimestamp';
import type { TimeRangeDescription } from './TimeRangeDescription';
import type { SummarySourceType } from './SummarySourceType';
import type { SummaryTier } from './SummaryTier';
import type { SummaryMetadata } from './SummaryMetadata';

export interface Summary {
  /** Primary key */
  id: SummaryId;

  /** Owner persona */
  persona_id: PersonaId;

  /** The compressed content (first-person narrative) */
  summary: string;

  /** Number of source entries/summaries that were compressed */
  message_count: number;

  // ═══════════════════════════════════════════════════════════════════════
  // TIME COVERAGE — Full datetime range
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Human-readable time range for display.
   * @example "Jan 27 10:30 to Jan 27 14:30 EST"
   */
  covered_range: TimeRangeDescription;

  /**
   * Machine-readable start of coverage (UTC).
   * The earliest timestamp among source entries.
   * Added in v24.
   */
  covered_start: ISOTimestamp;

  /**
   * Machine-readable end of coverage (UTC).
   * The latest timestamp among source entries.
   *
   * NOTE: This field is OPTIONAL — not yet in DB schema.
   * PROPOSED: Add column in v26 migration.
   * When v26 migration runs, remove the `?` to make this required.
   */
  covered_end?: ISOTimestamp | null;

  // ═══════════════════════════════════════════════════════════════════════
  // SOURCE TRACKING — What was compressed
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * What type of source this came from.
   * 'history' = from history entries (first pass)
   * 'summary' = from summaries (meta-summary)
   */
  source_type: SummarySourceType;

  /**
   * IDs of source entries.
   * - If source_type='history': these are HistoryId values
   * - If source_type='summary': these are SummaryId values
   *
   * Stored as JSON array in DB.
   */
  source_ids: number[];

  // ═══════════════════════════════════════════════════════════════════════
  // TIER SYSTEM — Where it lives in context
  // ═══════════════════════════════════════════════════════════════════════

  /** Which tier this summary belongs to. Added in v25 (explicit tier model). */
  tier: SummaryTier;

  /** Position within the tier for ordering. Lower = displayed first (newer). Added in v25. */
  tier_position: number;

  // ═══════════════════════════════════════════════════════════════════════
  // LIFECYCLE
  // ═══════════════════════════════════════════════════════════════════════

  /** When this summary was created */
  created_at: ISOTimestamp;

  /**
   * Soft delete timestamp.
   * - null = active
   * - timestamp = hidden (but recoverable)
   */
  archived_at: ISOTimestamp | null;

  /**
   * Lineage tracking — which summary replaced this one.
   * Used when summaries are consolidated.
   * - null = current version
   * - id = superseded by that summary
   */
  replaced_by_id: SummaryId | null;

  // ═══════════════════════════════════════════════════════════════════════
  // SEMANTIC RETRIEVAL (RAG)
  // ═══════════════════════════════════════════════════════════════════════

  /** Vector embedding for semantic search. Generated by Cloudflare AI embedding model. */
  embedding: ArrayBuffer | null;

  /** Which model generated the embedding */
  embedding_model: string | null;

  // ═══════════════════════════════════════════════════════════════════════
  // METADATA
  // ═══════════════════════════════════════════════════════════════════════

  /** Rich metadata extracted during summarization. Stored as JSON in DB. */
  metadata: SummaryMetadata | null;

  /**
   * Cached token count for this summary.
   * Used to avoid re-estimating tokens during context assembly.
   * Optional — falls back to estimation if not present.
   */
  token_count?: number;
}
