/**
 * Who created the media.
 *
 * - 'user' — uploaded by the human user (photos, voice messages)
 * - 'persona' — generated by an AI persona (art, synthesized speech)
 * - 'system' — created by system processes (thumbnails, format conversions)
 *
 * @downstream packages/media/src/Media — Media.source is this type
 * @upstream None — leaf discriminated union, no dependencies
 * @pattern discriminated-union — three exhaustive variants covering all authorship origins
 * @antipattern DO NOT add platform-specific sources here (e.g., 'telegram', 'web').
 *   Source describes WHO, not WHERE. Platform context belongs on domain subtypes.
 * @tested_by packages/media/__tests__/media.test.ts
 */
export type MediaSource = 'user' | 'persona' | 'system';
